---
# This playbook installs Virtualbox

- name: Download Virtualbox installer
  get_url:
    url=http://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo
    dest=/etc/yum.repos.d/virtualbox.repo

- name: Download repokey
  get_url: >
    dest={{ temp_dir }}/virtualbox.asc
    url=https://www.virtualbox.org/download/oracle_vbox.asc

- name: Import repokey
  shell: rpm --import {{ temp_dir }}/virtualbox.asc

- name: Update kernel to the latest version
  yum: name=kernel* state=latest

- name: Install required packages
  yum: name={{ item }} state=latest
  with_items:
    - binutils
    - gcc 
    - make 
    - patch 
    - libgomp 
    - glibc-headers 
    - glibc-devel 
    - kernel-headers 
    - kernel-devel
    - dkms

- name: Install Virtualbox package
  yum: name=VirtualBox-5.0 state=latest

- name: Update Virtualbox driver
  shell: /usr/sbin/rcvboxdrv setup

- name: Get current vbox version
  shell: rpm -qa | grep -i VirtualBox | cut -d '_' -f 1 | cut -d '-' -f 3
  register: vbox_version

- name: Download Extension Pack
  get_url:
    url=http://download.virtualbox.org/virtualbox/{{ vbox_version.stdout }}/Oracle_VM_VirtualBox_Extension_Pack-{{ vbox_version.stdout }}.vbox-extpack
    dest={{ temp_dir }}/Oracle_VM_VirtualBox_Extension_Pack-{{ vbox_version.stdout }}.vbox-extpack

- name: Install Extension Pack
  shell: vboxmanage extpack install {{ temp_dir }}/Oracle_VM_VirtualBox_Extension_Pack-{{ vbox_version.stdout }}.vbox-extpack

- name: Add system user to vbox group (this is needed e.g. for sharing USB devices)
  command: usermod -a -G vboxusers {{ user }}
