---
# This playbook installs Hashicorp Terraform
# unfortunately there're no fedora / rhel packages so
# we download zip and unarchive it
# in order to update your current installation you have to remove it manually
# or invoke playbook with "-e update_apps=true"

- name: Check if there is any old installation
  stat: path="{{ local_bin_dir }}/terraform"
  register: terraform_state

- block:
  - name: Download package
    get_url:
      # due to SSL bug: https://github.com/ansible/ansible/issues/25402
      validate_certs: no
      dest: "{{ temp_dir }}/terraform.zip"
      url: "https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip"

  - name: Ensure Terraform binary is removed
    file:
      path: "{{ local_bin_dir }}/terraform"
      state: absent

  - name: Extract archive
    unarchive:
      src: "{{ temp_dir }}/terraform.zip"
      dest: "{{ local_bin_dir }}/"
      group: "{{ group }}"
      owner: "{{ user }}"

  when: terraform_state.stat.exists == false or update_apps | default('') != ''
