---
# This playbook installs Skype

- name: Download Skype installer
  get_url:
    url=http://www.skype.com/go/getskype-linux-beta-fc10
    dest=/tmp/skype.rpm

- name: Install Skype package
  yum: name=/tmp/skype.rpm state=present
  register: output

- debug: msg="Skype installed; now configure manually"
  when: output.rc == 1
